version: '3.1'

services:

  db:
    image: mysql/mysql-server:latest
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Agenda
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 3
      start_period: 30s
      timeout: 10s
    networks:
      - sistema_agenda_net

networks:
  sistema_agenda_net:
    driver: bridge
